### ISSUE TITLE
플러그인 작동안함.

### ISSUE THREAD

**Issue by kmsimproject** [monun/battle-royale#1]
코틀린플러그인, protocollib 모두 넣어보았습니다만, 런타임오류인지 작동이 안됩니다.

[21:11:06 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:11:06 INFO]: Reloading ResourceManager: Default, bukkit
[21:11:07 INFO]: Loaded 7 recipes
[21:11:08 INFO]: Starting minecraft server version 1.16.5
[21:11:08 WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[21:11:08 INFO]: Loading properties
[21:11:08 ERROR]: Failed to read console input
java.io.IOException: 핸들이 잘못되었습니다
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_281]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_281]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_281]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_281]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67) ~[patched_1.16.5.jar:git-Paper-466]
	Suppressed: java.io.IOException: 핸들이 잘못되었습니다
		at java.io.FileInputStream.close0(Native Method) ~[?:1.8.0_281]
		at java.io.FileInputStream.access$000(Unknown Source) ~[?:1.8.0_281]
		at java.io.FileInputStream$1.close(Unknown Source) ~[?:1.8.0_281]
		at java.io.FileDescriptor.closeAll(Unknown Source) ~[?:1.8.0_281]
		at java.io.FileInputStream.close(Unknown Source) ~[?:1.8.0_281]
		at java.io.BufferedInputStream.close(Unknown Source) ~[?:1.8.0_281]
		at sun.nio.cs.StreamDecoder.implClose(Unknown Source) ~[?:1.8.0_281]
		at sun.nio.cs.StreamDecoder.close(Unknown Source) ~[?:1.8.0_281]
		at java.io.InputStreamReader.close(Unknown Source) ~[?:1.8.0_281]
		at java.io.BufferedReader.close(Unknown Source) ~[?:1.8.0_281]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:183) ~[patched_1.16.5.jar:git-Paper-466]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[patched_1.16.5.jar:git-Paper-466]
		at net.minecraft.server.v1_16_R3.DedicatedServer$1.run(DedicatedServer.java:67) ~[patched_1.16.5.jar:git-Paper-466]
[21:11:08 INFO]: This server is running Paper version git-Paper-466 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[21:11:08 INFO]: Debug logging is disabled
[21:11:08 INFO]: Server Ping Player Sample Count: 12
[21:11:08 INFO]: Using 4 threads for Netty based IO
[21:11:08 INFO]: Default game type: SURVIVAL
[21:11:08 INFO]: Generating keypair
[21:11:08 INFO]: Starting Minecraft server on *:25565
[21:11:08 INFO]: Using default channel type
[21:11:12 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[21:11:16 WARN]: Legacy plugin Kotlin v1.4.31.0 does not specify an api-version.
[21:11:16 ERROR]: Could not load 'plugins\BattleRoyale.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/monun/battleroyale/plugin/BattleRoyalePlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-466]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-466]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.UnsupportedClassVersionError: com/github/monun/battleroyale/plugin/BattleRoyalePlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-466]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[patched_1.16.5.jar:git-Paper-466]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-466]
	... 7 more
[21:11:16 INFO]: Loading Kotlin v1.4.31.0
[21:11:16 INFO]: Loading ProtocolLib v4.6.0
[21:11:16 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:11:16 INFO]: Enabling ProtocolLib v4.6.0
[21:11:16 INFO]: Started structure compiler thread.
[21:11:17 INFO]: Preparing level "world"
[21:11:17 INFO]: Preparing start region for dimension minecraft:overworld
[21:11:17 INFO]: Loaded 0 spawn chunks for world world
[21:11:17 INFO]: Preparing spawn area: 0%
[21:11:17 INFO]: Preparing spawn area: 0%
[21:11:17 INFO]: Time elapsed: 579 ms
[21:11:17 INFO]: Preparing start region for dimension minecraft:the_nether
[21:11:17 INFO]: Loaded 0 spawn chunks for world world_nether
[21:11:17 INFO]: Preparing spawn area: 0%
[21:11:17 INFO]: Time elapsed: 92 ms
[21:11:17 INFO]: Preparing start region for dimension minecraft:the_end
[21:11:18 INFO]: Loaded 0 spawn chunks for world world_the_end
[21:11:18 INFO]: Time elapsed: 184 ms
[21:11:18 INFO]: Enabling Kotlin v1.4.31.0*
[21:11:18 INFO]: Running delayed init tasks
[21:11:18 INFO]: Done (9.571s)! For help, type "help"
[21:11:18 WARN]: ************************************************************
[21:11:18 WARN]: * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[21:11:18 WARN]: * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[21:11:18 WARN]: * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[21:11:18 WARN]: *
[21:11:18 WARN]: * Please update the version of Java you use to run Paper
[21:11:18 WARN]: * to at least Java 11. When Paper for Minecraft 1.17 is
[21:11:18 WARN]: * released support for versions of Java before 11 will
[21:11:18 WARN]: * be dropped.
[21:11:18 WARN]: *
[21:11:18 WARN]: * Current Java version: 1.8.0_281
[21:11:18 WARN]: *
[21:11:18 WARN]: * Check this forum post for more information: 
[21:11:18 WARN]: *   https://papermc.io/java11
[21:11:18 WARN]: ************************************************************
[21:11:18 INFO]: Timings Reset
[21:11:21 INFO]: Plugins (2): §aKotlin*§f, §aProtocolLib

로그내용입니다. plugins에 넣어보았지만 작동하지않구요. 생존일지 플러그인도 마찬가지입니다.
어떻게 해야하나요?

**Comment by kmsimproject** [comment]
해결됬습니다. 죄송합니다.
